services:
  node:
    build: ./node
    ports:
      - target: ${INTERNAL_PORT}
        published: 0
        protocol: "udp"
        mode: "host"
    scale: ${NODE_INSTANCES}
    tty: true
    environment:
      HOST_NAME: "node"
      INTERNAL_PORT: ${INTERNAL_PORT}
      RUST_LOG: ${LOG_LEVEL}
      DISCOVER_SIBLINGS_INTERVAL_MS: 5000
      SIBLING_EXPIRY_TIME_MS: 15000
      SUSPICIOUS_INBOUND_MESSAGE_GAP_MS: 10000
